# The minimum and maximum corners of the spawn area (in chunks, not blocks). These chunks will always be loaded. Omit to disable the spawn area from being force loaded.
spawn_chunk_corners = [
    [-3, -3],
    [3, 3]
]
spawn_position = [-19.5, 22.0, 61.5]
# Yaw and pitch in degrees
spawn_rotation = [180.0, 0.0]
game_mode = "survival"
kill_oob_players = true
minimum_y_level = -20
chat_enabled = true
# Omit to disable the boss bar
boss_bar_text = "§9§oWelcome§r to the §l§cserver§r!"
boss_bar_color = "red"
# Check the wiki for valid division IDs: https://minecraft.wiki/w/Java_Edition_protocol/Packets#Boss_Bar
boss_bar_division = 1
# Omit to disable the title
title_text = "Welcome!"
# Note: subtext is only shown if the title is shown
title_subtext = "§2Enjoy your stay!"
# Note: title timings are in ticks (20 ticks = 1 second)
# Note: if you omit a time, it will default to 0
title_animation_enabled = false
title_fade_in = 20
title_stay = 50
title_fade_out = 20

# This is a list of parkour courses. Each course has a name and a list of checkpoints.
[[parkour]]
name = "Parkour 1"
# The first checkpoint is the start, and the last checkpoint is the end
# Note: all checkpoints must be reached linearly to complete the course (you can't skip checkpoints)
checkpoints = [[-29, 20, 55],[-50, 34, 17],[-20, 39, 66]]

# This is a list of text display entities.
[[text_displays]]
text = "§6Parkour!!"
position = [-28.5, 20.5, 55.5]
# Yaw, pitch, and roll in degrees
rotation = [60.0, -20.0, 0.0]
scale = [1.5, 1.5, 1.5]

# This is a list of item display entities.
[[item_displays]]
item = "diamond"
position = [-28.5, 21.3, 55.5]
# Yaw, pitch, and roll in degrees
rotation = [60.0, 0.0, 0.0]
scale = [0.5, 0.5, 0.5]